apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eqj6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-eqj6@sha256:82eea083ed3be38a64064edfe5b26df9fb9a7efaa5403b97601be45a6ea83fa1
        name: my-nodejs
        resources: {}
status: {}
